### ISSUE TITLE
npm-version-script.js

### ISSUE THREAD

**Issue by NorthernMan54** [homebridge/.github#24]
### Analysis

```
Error: Malformed branch name for ref: refs/heads/beta. Can't derive the base version. Use a branch name like: beta-x.x.x or alpha-x.x.x
[17](https://github.com/homebridge/node-pty-prebuilt-multiarch/actions/runs/7223513638/job/19682741679#step:8:18)
    at desiredTargetVersion (/home/runner/work/node-pty-prebuilt-multiarch/node-pty-prebuilt-multiarch/.github/npm-version-script.js:69:9)
[18](https://github.com/homebridge/node-pty-prebuilt-multiarch/actions/runs/7223513638/job/19682741679#step:8:19)
    at Object.<anonymous> (/home/runner/work/node-pty-prebuilt-multiarch/node-pty-prebuilt-multiarch/.github/npm-version-script.js:73:21)
[19](https://github.com/homebridge/node-pty-prebuilt-multiarch/actions/runs/7223513638/job/19682741679#step:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
[20](https://github.com/homebridge/node-pty-prebuilt-multiarch/actions/runs/7223513638/job/19682741679#step:8:21)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[21](https://github.com/homebridge/node-pty-prebuilt-multiarch/actions/runs/7223513638/job/19682741679#step:8:22)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
[22](https://github.com/homebridge/node-pty-prebuilt-multiarch/actions/runs/7223513638/job/19682741679#step:8:23)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
[23](https://github.com/homebridge/node-pty-prebuilt-multiarch/actions/runs/7223513638/job/19682741679#step:8:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
[24](https://github.com/homebridge/node-pty-prebuilt-multiarch/actions/runs/7223513638/job/19682741679#step:8:25)
    at node:internal/main/run_main_module:28:49
```

**Comment by bauer-andreas** [comment]
The current beta publishing script builds around a work flow where each beta branch name includes the version number. This allows to easily develop multiple beta lines at the same time (or properly separate them).
What is unexpected? Or what should change?

**Comment by NorthernMan54** [comment]
I was going to take a look at the code, and see if it is possible to tweak it and stop the exit(1) in this scenario.

The scenario was publishing a release of [node-pty-prebuilt-multiarch](https://github.com/homebridge/node-pty-prebuilt-multiarch) from a branch without the proper beta name format.  I was thinking maybe the code should look at the package.json version and adjust it based on that as a fall back.

Or is the beta/alpha branch name check there as protection against other issues ?
